name: Update Docs on Read the Docs

on:
  push:
    branches: [ main ] # 触发条件为推送到 main 分支

jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
          python-version: '3.x' # 使用 Python 3

    - name: Install Dependencies
      run: |
        pip install readthedocs-api-client
        pip install -r requirements.txt # 或者其他安装依赖的方式

    - name: Build Documentation
      run: |
        make html # 假设你使用的是 Sphinx 文档生成工具
      working-directory: docs # 如果你的文档位于子目录中

    - name: Deploy Documentation to Read the Docs
      run: |
          python - <<EOF
          import os
          from readthedocs_api_client.client import ReadTheDocsClient

          # 获取环境变量中的 RTD 令牌
          rtd_token = os.environ.get("READTHEDOCS_TOKEN")
          client = ReadTheDocsClient(rtd_token)

          # 构建文档
          response = client.builds.create(
              project="lm_select_test", # 替换为你的 Read the Docs 项目的名称
              data={"state": "triggered"}
          )
          print(response)
          EOF
      env:
        READTHEDOCS_TOKEN: ${{ secrets.READTHEDOCS_TOKEN }}
